import matplotlib.pyplot as plt
import pandas as pd

# Load the data generated by main.cc
df = pd.read_csv('results.csv')
df = df.sort_values(by='MB')

plt.figure(figsize=(10, 6))
plt.plot(df['MB'], df['CPU_ms'], 'o-', label='CPU (OpenMP+SIMD)', color='red')
plt.plot(df['MB'], df['GPU_ms'], 's-', label='GPU (CUDA)', color='blue')

plt.yscale('log')
plt.xlabel('Data Size (MB)')
plt.ylabel('Time Taken (ms)')
plt.title('Scaling Performance: CPU vs GPU')
plt.legend()
plt.grid(True, which="both", alpha=0.3)

plt.savefig('performance_scaling.pdf', format='pdf', bbox_inches='tight')
plt.show()